### ISSUE TITLE
Request docker build environment

### ISSUE THREAD

**Issue by Werneror** [lexfo/sshimpanzee#1]
The project looks wonderful! I would like to try it out, but I'm having a lot of trouble - I can't get openssh-portable to compile successfully. I'm getting a lot of errors when compiling openssh-portable, and I've solved some of them, but I'm getting a lot more. I guess there is something wrong with my build environment. Is it possible to provide a docker container in which openssh-portable can be compiled successfully?

**Comment by TitouanLazard** [comment]
Hello, 
The docker file is a good idea, i'll try to provide one.

In the meantime could you provide information about the compilation errors you ran into ? musl is supposed to handle openssh compilation, and sshimpanzee was designed to remove most of the external dependacies.

**Comment by TitouanLazard** [comment]
Hi,

This is a first draft of a dockerfile :
```
FROM alpine:latest

COPY . build_root
WORKDIR build_root

RUN apk add autoconf gcc make  python3 git automake musl-dev build-base openssh-keygen
RUN git submodule init; git submodule update; true
RUN python builder.py -r 127.0.0.1:9200 -vvv --force-clean-build --no-musl --compiler gcc
```

**Comment by Werneror** [comment]
Thank you very much for the dockerfile, I will try to use it later.

The error I encountered was:

```
cc: error: unrecognized command line option '-static-pie'; did you mean '-static'?
```

This could be a very simple mistake. But I'm very novice and not capable of fixing it.

The complete log is in the file [config.log](https://github.com/lexfo/sshimpanzee/files/11651577/config.log).

**Comment by TitouanLazard** [comment]
hi,

This has been fixed on the experimental branch (pushed few days ago), you can try it, or simply remove the "--static-pie" on line 131:
`configure_command = f'cd openssh-portable; ./configure --without-zlib --disable-lastlog --disable-utmp --disable-utmpx --disable-wtmp --disable-wtmpx --disable-libutil --without-openssl CFLAGS="-D_FORTIFY_SOURCE=0 -static-pie -static -Os -fPIC {CFLAGS_add} {args.extra_cflags}" LDFLAGS="-static-pie -static {LFLAGS_add} {args.extra_ldflags}" CC="<COMPILER>"  --without-sandbox --with-privsep-user=root --with-privsep-path=/tmp/  --with-pie`

**Comment by Werneror** [comment]
> hi,
> 
> This has been fixed on the experimental branch (pushed few days ago), you can try it, or simply remove the "--static-pie" on line 131: `configure_command = f'cd openssh-portable; ./configure --without-zlib --disable-lastlog --disable-utmp --disable-utmpx --disable-wtmp --disable-wtmpx --disable-libutil --without-openssl CFLAGS="-D_FORTIFY_SOURCE=0 -static-pie -static -Os -fPIC {CFLAGS_add} {args.extra_cflags}" LDFLAGS="-static-pie -static {LFLAGS_add} {args.extra_ldflags}" CC="<COMPILER>" --without-sandbox --with-privsep-user=root --with-privsep-path=/tmp/ --with-pie`

After removing `--static-pie`, `configure` runs successfully. When executing `make` in the `openssh-portable` directory, I encountered a new error:

```
musl-gcc -o ssh-add ssh-add.o ssh-sk-client.o -L. -Lopenbsd-compat/ -static   -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -pie  -lssh -lopenbsd-compat  
./libssh.a(authfile.o): In function `sshkey_load_private_type':
authfile.c:(.text+0x4c0): undefined reference to `options'
collect2: error: ld returned 1 exit status
Makefile:216: recipe for target 'ssh-add' failed
make: *** [ssh-add] Error 1
```

**Comment by Werneror** [comment]
> Hi,
> 
> This is a first draft of a dockerfile :
> 
> ```
> FROM alpine:latest
> 
> COPY . build_root
> WORKDIR build_root
> 
> RUN apk add autoconf gcc make  python3 git automake musl-dev build-base openssh-keygen
> RUN git submodule init; git submodule update; true
> RUN python builder.py -r 127.0.0.1:9200 -vvv --force-clean-build --no-musl --compiler gcc
> ```

After changing the `python` in the last line to `python3`, it compiles successfully by using this dockerfile.

**Comment by TitouanLazard** [comment]
Hi,
I pushed a more complete Dockerfile on the experimental branch, everything should be working . It should allow everyone to build sshimpanzee for x64 and ARM. I added building information in the README.
I'll close this issue soon.

**Comment by TitouanLazard** [comment]
Hi,

A new version of sshimpanzee is available with a docker build file. #2 
This should solve compilation issues in most cases.
